version: '3.9'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow-webserver:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__FERNET_KEY: "somethingrandom"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql://airflow:airflow@postgres:5432/crypto"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade &&
               airflow users create
                 --username admin
                 --password admin
                 --firstname Admin
                 --lastname User
                 --role Admin
                 --email admin@example.com &&
               airflow webserver"

  airflow-scheduler:
    build: ./airflow
    depends_on:
      - airflow-webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: "airflow scheduler"

  spark:
    build: ./spark
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: crypto
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

volumes:
  postgres_data:
